### ISSUE TITLE
ReferenceError: id is not defined

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-shure-wireless#3]
I get this error as soon as I click update config on a new instance.

```
Uncaught Exception:
ReferenceError: id is not defined
    at instance_api.updateReceiver (/Users/technician/companion/companion2/companion/lib/module/shure-wireless/internalAPI.js:728:36)
    at instance.processShureCommand (/Users/technician/companion/companion2/companion/lib/module/shure-wireless/index.js:319:14)
```

Line 728:
```javascript
else if (key =='HIGH_DENSITY' || id == 'TRANSMISSION_MODE') {
     if (value == 'STANDARD') {
          value = 'OFF';
     }
     else if (value == 'HIGH_DENSITY') {
          value = 'ON';
     }

     this.receiver.highDensity = value;
     this.instance.setVariable('high_density_mode', value);
}
```

Not sure if `id` should be a different variable or if it's not global and should be.

The error keeps popping up as data is received.

**Comment by krocheck** [comment]
@josephdadams yeah, `id` should be `key`.  Can you do that quick edit in your dev and see if any others pop up?

**Comment by josephdadams** [comment]
Made the edit, immediately started getting this instead:

```
Uncaught Exception:
TypeError: Cannot read property '0' of null
    at instance.processShureCommand (/Users/technician/companion/companion2/companion/lib/module/shure-wireless/index.js:340:37)
```

Line 340:
```javascript
commandNum = parseInt( commandArr[0].substr(0,1) );
```

**Comment by haakonnessjoen** [comment]
Try to add `commandArr = command.split(' ');` between line 339 and 340.

**Comment by krocheck** [comment]
👍  ... that and other errors located.

**Comment by josephdadams** [comment]
We are waaaaay ahead of you @haakonnessjoen :)

**Comment by haakonnessjoen** [comment]
Sorry for trying to help 😥

;) 👍
